spring:
  main:
    banner-mode: 'off'
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
logging:
  pattern:
    console: '%d{yyyy-MM-dd-HH:mm:ss.SSS} [%-5level] [%X{loginId}] %logger - %msg%n'
  level:
    root: WARN
    operation: INFO
    cherry: TRACE
    org:
      springframework: INFO
